#CLASSE(PROJETO, PADRÃO, MODELO)
#INSTACIAR = CRIAR UM OBJETO APARTIR DA CLASSSE
#A CLASSE TEM DOIS COMPONENTES: ATRIBUTOS(QUALIDADE, AQUILO QUE QUALIFICAR,
#CARACTERISTICAS) E METODOS(AÇÕE, O QUE OBJETO FAZ)
#ATRIBUTOS: VÃO TRABALHAR COM VARIAVEIS(PARA GUARDAR, EX: UMA COR DE CARRO)
#METODOS: USAR FUNÇÕEOS
#API: NA PRATICA ELA É INTERPRETADA ATRVAES DE UM METODOS PARA TROCAS INFORMAÇÕES
#OBJETOS TROCAM INFORMAÇOES/MENSAGENS ENTRE SI.
#METODOS SÃO FUNÇÕES, E NÃO AO CONTRARIO
#4 PILARES DA PROGRAMAÇÃO ORIENTADA A OBJETOS:
# -ABSTRAÇÃO: PARA USAR NÃO PRECISA SABER O QUE ESTÁ POR TRÁS)
# -HERANÇA(CLASSE HEDAER DE OUTRA CLASSE ATRIBUTOS E METODOS- ESTÁ DOANDO
#E EXISTEM SUPERCLASSESCLASSES, SUBCLASSES).
# -EMCAPSULAMENTO: É PROTEGER, QUEM PODE ALTERAR
# - POLIMORFISMO: MUITAS FORMAS, RESCREVER UMA FUNÇÃO PARA FAZER OUTRA(MANTENDO O MESMO NOME)

